### ISSUE TITLE
Install on xampp on port 8081 and mysql port 3312

### ISSUE THREAD

**Issue by albu77** [schspain/adive-php7#2]
IS there a doc section indicating the settings to change the ports value

*I change    'SERVER_PORT' => 8081, in environment.php
And add the following
 'database.port' => '3312',
and $db = new PDO('mysql:host=' . $API->config('database.host') . 
             ';port=' . $API->config('database.port') .
in config.php
But doesn't seems to work totally

**Comment by ferdinandmartin** [comment]
In config.php use the port standard configuration as a PDO standard like this:

$dsn = 'mysql:dbname=testdb;host=127.0.0.1;port=3333';

You can create all different connections you need here, and then pass it to the method like this:

$API->get('/hello/{var}', function($var) use($API,$dsn) {
    $API->render('Default:hello', array(
        'title' => 'Hello World!',
        'example' => $var
    ));
});

This must work nice, but if you still have problems contact me and we try to solve it.

Thank you!!
